name: reflectable
version: 2.1.0
description: >
  Reflection support based on code generation, using 'capabilities' to
  specify which operations to support, on which objects.
author: Dart Team <misc@dartlang.org>
homepage: https://www.github.com/dart-lang/reflectable
environment:
  sdk: '>=1.12.0 <3.0.0'
dependencies:
  analyzer: '>=0.35.0 <0.37.0'
  build: any # ^1.0.0 DEBUG
  build_resolvers: any # '>=0.2.0 <2.0.0' DEBUG
  build_config: any # ^0.3.0 DEBUG
  build_runner: any # ^1.3.0 DEBUG
  build_runner_core: any # ^3.0.0 DEBUG
  dart_style: any # '>=0.2.0 <2.0.0' DEBUG
  glob: any # ^1.1.0 DEBUG
  logging: any # ^0.11.0 DEBUG
  package_config: any # ^1.0.0 DEBUG
  package_resolver: any # ^1.0.0 DEBUG
  path: any # '>=1.2.0 <2.0.0' DEBUG
  source_span: any # ^1.0.0 DEBUG
dev_dependencies:
  build_test: any # ^0.10.0 DEBUG
  test: any # ^1.3.0 DEBUG
