name: coverage_reflectable
version: 0.5.1
description: A simple console application.
dependencies:
  observatory:
    path: /usr/local/google/home/eernst/devel/dart/work/sdk/runtime/observatory
  observe: any
  analyzer: '^0.27.0'
