name: test_reflectable
dependencies:
  reflectable:
    path: ../reflectable
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
transformers:
- reflectable:
    $include: ["test/*.dart"]
    entry_points:
      - test/metadata_test.dart
      - test/import_reflectable.dart
      - test/use_annotation.dart
      - test/reflect_test.dart
      - test/export_test.dart
      - test/use_prefix_test.dart
      - test/three_files_test.dart
      - test/invoke_test.dart
      - test/members_capability_test.dart
      - test/annotated_classes_test.dart
      - test/reflect_type_test.dart
      - test/declarations_test.dart
      - test/new_instance_test.dart
# Disabled next three entries to avoid failing transformation
#      - test/new_instance_default_values_test.dart # Issue # 8
#      - test/capabilities_test.dart
#      - test/member_capability_test.dart
#      - test/serialize_test.dart
#      - test/basic_test.dart
# Our test-script will invoke dart2js on all the files in build/test, so
# we leave it out here.
- $dart2js:
    $include: []
