name: reflectable
description: >
  Reflectable is a library that allows programmers to reduce certain
  usages of dynamic reflection to a transformer generated specialization
  of the same thing that does not use dynamic reflection, thus improving
  the performance of (esp. Dart2JS) generated code.
version: 0.0.1
author: The Dart Team <dart@google.com>
homepage: https://www.github.com/dart-lang/reflectable
dependencies:
  analyzer: '^0.25.0'
  barback: '^0.15.0'
  code_transformers: '^0.2.0'
  logging: '^0.11.0'
dev_dependencies:
  unittest: '^0.11.0'
transformers:
- reflectable/src/transform_import:
    $include: lib/reflectable.dart
- $dart2js:
    commandLineOptions: [--show-package-warnings]
    # We do not want to compile anything in this package.
    $include: []
