name: reflectable
description: >
  This package allows programmers to reduce certain usages of dynamic
  reflection to a transformer generated specialization with the same
  behavior. The generated code does not use dynamic reflection and thus
  improves the performance of (esp. dart2js) generated code.
version: 0.3.3
author: The Dart Team <dart@google.com>
homepage: https://www.github.com/dart-lang/reflectable
environment:
  sdk: ">=1.12.0 <2.0.0"
dependencies:
  analyzer: '^0.26.1+10'
  barback: '^0.15.0'
  code_transformers: '^0.2.0'
  dart_style: '^0.2.0'
  logging: '^0.11.0'
dev_dependencies:
  unittest: '^0.11.0'
dependency_overrides:
  analyzer: 0.26.1+14
transformers:
- reflectable/src/transform_import:
    $include: lib/reflectable.dart
- $dart2js:
    commandLineOptions: [--show-package-warnings]
    # We do not want to compile anything in this package.
    $include: []
